### ISSUE TITLE
NoData error when using ig_user_id of public account 

### ISSUE THREAD

**Issue by christianrochford** [johnfmorton/Pic-Puller-Lite-for-Instagram#1]
I'm using the media_recent function to pull in the latest pics from a public account, I've set the user_id and the ig_user_id and have authorized the app using the advanced method, however, I'm getting the NoData error

`{exp:ig_picpuller:media_recent limit="6" user_id="1" ig_user_id="1088353513" use_stale_cache="no"}
		 {if ig_status == 'true'}
		<img id="instagram-{count}" src="{ig_standard_resolution}" alt="" />
		{/if}
		 {if ig_status == 'false'}
		  <p>ERROR TYPE: {ig_error_type}</p>
		  <p>ERROR MESSAGE: {ig_error_message}</p>
		 {/if}
		{/exp:ig_picpuller:media_recent}`

**Comment by johnfmorton** [comment]
Hi Christian,

I think you're posting here, the Lite version of Pic Puller which does not have the feature you're asking about, but are referring to the Full version of Pic Puller. There is a support forum for the full version here:

[https://devot-ee.com/add-ons/support/pic-puller-for-instagram/viewforum/1938](https://devot-ee.com/add-ons/support/pic-puller-for-instagram/viewforum/1938)

In the mean time, I did try pulling the feed for the ig_user_id on my end using the same function and it's working for me. I've also simply cut and paste your code into a template on my end and it worked as expected. If you could post in the EE Pic Puller forum or send me an email, I'm sure we'll get to the bottom of this. Thanks.

-John
